site:
  title: Atom Console Docs
  #url: https://Atom.docs.com
  start_page: main::AR Engine/glossary.adoc
content:
  sources:
  - url: https://github.com/ten1251/AtomConsole.git
    branches: [main]
    start_path: src
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [main]
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
runtime:
  fetch: true