= AR Engine API 

Для обмена данными и управляющими сообщениями между AR Engine и его компонентами, SWP, приложениями, используется специально разработанное API. 

== Описание функций 

void start ( ) virtual 

Функция, переопределяемая пользователем и вызываемая API при запуске приложения. Удобно использовать для установки первоначальных настроек и подписок на телеметрию. 


void stop ( ) virtual 

Функция, переопределяемая пользователем и вызываемая API при завершении работы программы

== Обращение к функциям API 

Если обычно функции вызываются по её названию, и с указанием аргументов в круглых скобках, то обращение к функциям API отличается от стандартного. Это связано с гибкостью предоставляемого API. Шаблон вызова функции API выглядит следующим образом: 

api("имя_функции", "аргумент_1", "аргумент_2".., "аргумент_9"),  

где имя_функции - строковое название функции из таблицы раздела «Функции API», а аргументы 1-9 - допустимое количество аргументов, передаваемых с функцией. Все 9 аргументов указывать нет необходимости, указываются только те, что требуются для функции. Список аргументов есть в таблице раздела «Функции API». 

Пример обращения к API для подписки на телеметрию скорости с обработкой в функции set_speed ( ), потребуется написать следующее: 

api("subscribe_to", "speedometer", "set_speed") 
