= Document Title (Level 0)
:toc:

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

===== Level 4 Section Title

====== Level 5 Section Title

== Another Level 1 Section Title

== Общая информация
[WARNING]
====
Если у нас не получится проверить ваш проект, мы не сможем его опубликовать.
====

Укажите `Возрастное ограничение` при публикации приложения или его новой версии, _если с обновлением_ появился потенциально недопустимый контент для определенной возрастной группы. Эта информация поможет пользователям *Store* принять решение об установке приложения

== Как правильно выбрать

[TIP]
====
Вы можете указать приблизительное возрастное ограничение. Наш модератор проверит ваш продукт перед публикацией, даст ценные советы и предложит изменения, если сочтет это будет необходимо, чтобы обеспечить соответствие заявленного возрастного ограничения реальности.
====

Ориентируйтесь на нашу краткую таблицу:

| Ограничения | Характеристики |
|-------------|----------------|
| 3+ | Без насилия, непристойного контента (оскорблений, ругательств). Не рекомендуется детям до 3 лет. Обратите внимание, что не все приложения с этим возрастным ограничением разработаны специально для детей |
| 7+ | Некоторое насилие и страшные сцены. Не рекомендуется детям до 7 лет. Обратите внимание, что не все приложения с этим возрастным ограничением разработаны специально для детей |
| 12+ | Умеренное насилие, страшные сцены, непристойный контент. Не рекомендуется детям до 12 лет. |
| 16+ | Насилие или сексуальный контент. Не рекомендуется детям до 16 лет. |
| 18+ | Высокий уровень насилия, сексуальный контент, упоминание наркотиков или алкоголя. Рекомендуется только для взрослых. |

=== Пример кода
Для приложений, link:https://docs.github.com/ru/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/quickstart-for-writing-on-github[опубликованных в Store], работает система возрастных ограничений. 
Ограничения помогают пользователям понять, содержит ли приложение потенциально 
#недопустимый контент# для людей определенного возраста

[.underline]#cores#

[.line-through]#ten# twenty VMs.

[source,bash]
----
curl -L -X POST 'https://api.example.com/v2/oauth' 
-H 'Content-Type: application/x-www-form-urlencoded' 
-H 'Accept: application/json' 
-H 'RqUID: <уникальный_идентификатор_запроса>' 
-H 'Authorization: Basic <ваш_authorization_key>' 
--data-urlencode 'scope=API_SCOPE'
----

