= AR Engine Emuliator

== Интерфейс 

*Эмулятор DataPlayer* – это программа, проигрывающая сценарии использования автомобиля в формате видеороликов с телеметрическими данными и имитирующая работу AR Engine API для запуска и тестирования пользовательских ATM приложений. 

При запуске программы можно наблюдать сценарий по умолчанию, представленный на рисунке выше. 

Интерфейс программы прост: он представляет из себя занимающую наибольшее место область воспроизведения видео с проекцией HUD, где запускается пользовательское приложение, и небольшое окно справа для некоторого управления приложением. В сценарии по умолчанию в правом окне можно в ручном режиме изменять телеметрические данные. 

Если выбрать и запустить некоторый сценарий, отличный от варианта по умолчанию, правое окно изменится и будет отображать часть телеметрических данных, воспроизводимых из сценария, а так же появятся кнопки для паузы и остановки сценария. 

== Функционал 

На текущий момент эмулятор DataPlayer предоставляет стандартный сценарий, запускаемый по умолчанию, где ролик не сопровождается телеметрическими данными. Вместо них пользователю предоставляется возможность в ручном режиме изменять их с помощью ползунков. В момент их изменения, эти данные будут регистрироваться через аналог AR Engine API и пересылаться до приложений, если последние подписаны на эти телеметрические данные. 

Помимо сценария по умолчанию есть 2 предзаготовленных сценария, поставляющиеся с программой: "Scene A" и "Scene B". 
