= Форматы файлов 

== Формат .arengine 

".arengine" - это описательный формат проекта atm приложения, создаваемого в AR Engine Builder. 

=== Описание  

Appinfo 

Application 

=== Пример файла 

Формат представляет из себя JSON-словарь, содержащий 2 основных раздела: 

appinfo; 

application. 

Описание 

Appinfo 

Этот раздел содержит информацию о проекте и его конфигурации, настройках. Этот раздел содержит следующие поля: 

 "project_name" -  название проекта, тип строковый; 

"application_version" - версия приложения, тип строковый; 

"application_build" - версия сборки приложения, тип строковый; 

"application_icon" - путь к иконке проекта, тип строковый; 

"application_name" - название приложения, тип строковый; 

"application_description" - описание приложения (скорее всего для магазина и менеджера приложений в AR Engine), тип строковый; 

"pack_appinfo" - флаг сохранения информации "app info" в приложении ((предупреждение) неактуально, скоро будет вырезано), тип логический. 

Application 

Иерархическое древо AR-элементов с описанием их метаданных и используемых ресурсов. В описании каждого AR элемента в "atm." указывается 

"class" - название класса AR элемента, тип строковый; 

"properties" - перечисление начальных значений мета AR элемента, тип массив массивов; 

"children" - перечисление дочерних AR элементов у текущего AR элемента, тип массив. 

Поле "class" полностью соответствует названию AR класса. Список AR классов и их имен можно посмотреть здесь ((предупреждение) здесь будет ссылка на AR классы). 

При экспорте данных в ".arengine" файл метаданные передаются только те поля, значения которых отличаются от значений по умолчанию, за исключением поля "name" - оно обязательно присутствует. Полный список возможных мета у AR элементов можно посмотреть здесь ((предупреждение) здесь будет ссылка на AR классы). 

Поле "children" может отсутствовать, если у рассматриваемого AR элемента нет дочерних. 

=== Пример файла 

Ниже приведен пример файла arengine проекта AR Engine Builder. 

Приложение "test", версии "0.0.1:1". В его составе 3 AR элемента: 

ARMain  

ARLabel 

ARImage 

У ARMain есть скрипт scripts/2332823745.arscript. 

У ARLabel есть скрипт scripts/2506451395.arscript. 

У ARImage есть установленное пользователем изображение "images/AccCapacityIcon.png". 

Фигура 

{ 

"appinfo": { 

"project_name": "test", 

"application_version": "0.0.1", 

"application_build": "1", 

"application_icon": "res://resources/icon.png", 

"application_name": "test", 

"application_description": "test application", 

"pack_appinfo": true 

}, 

"application": { 

"class": "ARMain", 

"properties": [ 

[ "name", "Main" ], 

[ "ar_script", "scripts/2332823745.arscript" ] 

], 

"children": [ 

{ 

"class": "ARLabel", 

"properties": [ 

[ "name", "ARLabel" ], 

[ "width", 965 ], 

[ "height", 197 ], 

[ "ar_script", "scripts/2506451395.arscript" ], 

[ "text", "SomeText" ],  

[ "font_size", 200 ] 

] 

}, 

{ 

"class": "ARImage", 

"properties": [ 

[ "name", "ARImage" ], 

[ "top", 217 ], 

[ "left", 40 ], 

[ "width", 256 ], 

[ "height", 256 ], 

[ "image", "images/AccCapacityIcon.png" ] 

== Формат .atm 

".atm" - это описательный формат сторонних atm приложений для AR Engine. 

Описание  

Appinfo 

Application 

Resources 

Пример файла 

Формат представляет из себя JSON-словарь, содержащий 3 основных раздела: 

appinfo; 

application; 

resources. 

Описание 

Appinfo 

Это раздел, описывающий общую информацию о проекте и её разработчике. В этом разделе возможны следующие поля: 

 "project_name" -  название проекта ((предупреждение) неактуально, скоро будет вырезано), тип строковый; 

"application_version" - версия приложения, тип строковый; 

"application_build" - версия сборки приложения, тип строковый; 

"application_icon" - путь к иконке проекта ((предупреждение) пока не знаем, как его хранить и обрабатывать), тип строковый; 

"application_name" - название приложения, тип строковый; 

"application_description" - описание приложения (скорее всего для магазина и менеджера приложений в AR Engine), тип строковый; 

"pack_appinfo" - флаг сохранения информации "app info" в приложении ((предупреждение) неактуально, скоро будет вырезано), тип логический. 

Application 

Иерархическое древо AR-элементов с описанием их метаданных и используемых ресурсов. В описании каждого AR элемента в "atm." указывается 

"class" - название класса AR элемента, тип строковый; 

"properties" - перечисление начальных значений мета AR элемента, тип массив массивов; 

"children" - перечисление дочерних AR элементов у текущего AR элемента, тип массив. 

Поле "class" полностью соответствует названию AR класса. 

При экспорте данных в ".atm" файл метаданные передаются только те поля, значения которых отличаются от значений по умолчанию, за исключением поля "name" - оно обязательно присутствует. 

Поле "children" может отсутствовать, если у рассматриваемого AR элемента нет дочерних. 

Resources 

Раздел с перечислением всех ресурсов проекта. Под ресурсом подразумевается не внутренний тип AR Engine, используемый в приложении, а непосредственно файлы изображения, 3D-модели, скрипта и прочего в поддерживаемом расширении. 

(предупреждение)При экспорте ".atm" запаковываются все файлы ".png" и ".arscript", что лежали в этот момент в папке с проектом. 

Данные в этом разделе хранятся как словарь, где относительное (от пути проекта) имя ресурса является ключом, а значением raw данные ресурса. Данные могут храниться как в неизменном виде, так и зашифрованные в Base64. 

