= Руководства

== Использование SceneTreeTween 

Функция create_animation позволяет легко анимировать любые параметры вашего скрипта и текущего класса. Аргументами функции являются: 

1) название переменной (String), 

2) начальное значение параметра (Variant),  

3) конечное значение параметра (Variant), 

4) время движения до начального значения (float), 

5) время движения до конечного значения (float), 

6) тип перехода (int, линейный, нелинейный), 

7) количество повторений (int, -1 повторять анимацию бесконечно) 
 
Функция возвращает объект типа SceneTreeTween. 
 
Простейший пример использования: 

extends ARImage 
 
var left_anim : SceneTreeTween 
 
var width_anim : SceneTreeTween 
 
var self_paint_anim : SceneTreeTween 
 
func _ready(): 
 
    #Аргументы функции: 
  
  1) название переменной (String), 
  
  2) начальное значение параметра (Variant), 
  
  3) конечное значение параметра (Variant), 
  
  4) время движения до начального значения (float), 
  
  5) время движения до конечного значения (float), 
  
  6) тип перехода (int, линейный, нелинейный), 
  
  7) количество повторений (int, -1 повторять анимацию бесконечно) 
 
    left_anim = create_animation("left", 0, 1200.0, 2.0, 4.0, Tween.TRANS_ELASTIC, -1) 

    width_anim = create_animation("width", 256, 512, 3.0, 4.5, 0) 
 
    self_paint_anim = create_animation("self_paint", Color.white,Color.red, 3.0, 4.0)  

func start(): 

    api('subscribe_to', 'accelerator', 'on_accelerator_changed') 

func on_accelerator_changed(data : String): 

    #включения выключения анимации по обращению к SceneTreeTween (left_anim ) 
 
    var value = float(data) 
 
    if value > 0.5: 

        left_anim.stop() 
 
    else: 
 
        left_anim.play() 

== Использование спрайт-листов 

=== Введение 

Элемент ARImage предоставляет базовый функционал для создания анимаций в совокупности со спрайт листами. 

Далее будет рассмотрены следующие темы: 

Спрайт лист и его подготовка 

Анимация по кадрам 

Анимация по координатам 

=== Спрайт-лист и его подготовка 

Спрайт лист - это изображение, которое содержит набор спрайтов. При работе со спрайт листами в ARImage есть некоторые ограничения: 

спрайты в спрайт листе должны располагаться по сетке фиксированного размера 

размеры спрайтов в спрайт листе должны быть одинакового размера 

между спрайтами и границами всего изображения в спрайт листе не должно быть отступов 

спрайты одной анимации не должны иметь между собой пустые места 

Если ваш спрайт лист соответствует этим критериям, то можно приступать к созданию анимации с его использованием. 

=== Анимация по кадрам

В ARImage есть возможность переключаться между кадрами, нарезанными с помощью заданных свойств h_frames, v_frames. 

Создадим новый проект в ARE Builder и добавим ARImage. Загружаем в папку проекта image спрайт лист "lifepotion.png". Выбираем его в свойствах image. 

Во вьюпорте отображается всё изображение, хотя нам необходимо отображать одновременно один спрайт из спрайт листа. Укажем количество горизонтальных кадров в h_frames (в текущем спрайт листе - 4). 

Теперь, с помощью изменения frame можно указывать, какой из спрайтов спрайт листа нужно отобразить. Раз делим на 4 элемента, то спрайты имеют индексы от 0 до 3. Нумерация спрайтов спрайт листа идет слева направо, сверху вниз. 

Учитывая, что спрайт лист одномерный, т.е. все спрайты располагаются в ряд, свойство frame и frame_coord.x совпадают. Это свойство можно менять как вручную, создавая один и тот же элемент с разным отображаемым спрайтом, так и через код. 

=== Анимация по координатам 

Теперь добавим новый ARImage к текущему проекту. Рассмотрим более сложный вариант спрайт листа, где спрайты располагаются и в ряд и в столбец. Загрузим "dwarf_guardian-m-001.png" в только созданный ARImage и установим h_frames = 3, а v_frames = 4. Размер дварфа больше в 2 раза по каждой размерности, поэтому я установил размер width и height на 256. 

На этом спрайт листе в каждом ряду располагаются анимации перемещения вверх/вниз/вправо/влево, поэтому чтобы не проверять или считать каждый раз, какой номер кадров на какую анимацию, воспользуемся свойствами frame_coord. При изменении frame_coord по оси x меняется кадр анимации дварфа в одном направлении, а по оси y - направление дварфа. 

Запрограммируем перемещение персонажа с этими анимациями и с помощью магии кода персонаж оживает: 


