site:
  title: Atom Console Docs
  #url: https://Atom.docs.com
  start_page: main::index.adoc
content:
  sources:
  - url: https://github.com/ten1251/AtomConsole.git
    branches: [main, AV-2073]
    start_path: src
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [main]
    start_path: docs

ui:
  bundle:
    url: /Users/nikita/Documents/Atom Documentation Antora/ui-bundle
    snapshot: true
runtime:
  fetch: true